name: PR Auto-Assignment
run-name: "Assigning reviewers for PR #${{ github.event.pull_request.number }}"
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - main

permissions:
  contents: read

jobs:
  pr-auto-assign:
    name: "Auto-assign Reviewers to PR #${{ github.event.pull_request.number }}"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: "Check if PR is from a fork"
        run: |
          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.event.pull_request.base.repo.full_name }}" ]; then
            echo "⚠️ Pull request is from a fork — skipping assignee assignment (no write permissions)."
            exit 0
          fi

      - name: "Checkout Repository"
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: "Assign Reviewers"
        uses: netcracker/qubership-workflow-hub/actions/pr-assigner@0eefd4976131d113c986281eed8bc642b6da303d # v2.8.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
